apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-scope-op
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-scope-op
  template:
    metadata:
      labels:
        name: cluster-scope-op
    spec:
      serviceAccountName: cluster-scope-op
      containers:
        - name: cluster-scope-op
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - cluster-scope-op
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-scope-op"
