apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "foo.example.com/v1alpha1",
          "kind": "Foo",
          "metadata": {
            "name": "example-foo"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: cluster-scope-op.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Foo is the Schema for the foos API
      kind: Foo
      name: foos.foo.example.com
      version: v1alpha1
  description: Placeholder description
  displayName: Cluster Scope Op
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - cluster-scope-op
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - foo.example.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: cluster-scope-op
      deployments:
      - name: cluster-scope-op
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: cluster-scope-op
          strategy: {}
          template:
            metadata:
              labels:
                name: cluster-scope-op
            spec:
              containers:
              - command:
                - cluster-scope-op
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: cluster-scope-op
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: cluster-scope-op
                resources: {}
              serviceAccountName: cluster-scope-op
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: cluster-scope-op.v0.0.0
  version: 0.0.1
